### ISSUE TITLE
Next steps for GitHub Campus Advisors process

### ISSUE THREAD

**Issue by arelia** [Campus-Advisors/campus-advisor-training-KalifiaBillal#10]
👋 Hello, your Campus Advisor training needs updates on [assignment module 2.3](https://github.com/Campus-Advisors/campus-advisor-training-KalifiaBillal/issues/7#issuecomment-664109274). Please complete that and we'll be happy to process your request for certification.

Once you have re-submitted the assignment, please reapply for the GitHub Campus Advisor program via the [offer in the Teacher Toolbox](https://education.github.com/toolbox/offers).

**Comment by khlaifiabilel** [comment]
Thank you, @Arelia, for you help, I have updated the Assignment in the Module 2.3 and I have re-submitted the offer in the Teachers Box.
