### ISSUE TITLE
Missing Module 4.1

### ISSUE THREAD

**Issue by arelia** [Campus-Advisors/campus-advisor-training-KalifiaBillal#9]
👋 Hi @KalifiaBillal  you are missing the Module 4.1 Assignment. Please post it here in this thread.

**Comment by khlaifiabilel** [comment]
Module 4.1 Assignment
![Screenshot from 2020-07-01 22-06-13](https://user-images.githubusercontent.com/31816208/86291629-2c1a9300-bbe7-11ea-99b4-9750eb50a195.png)
